apiVersion: v1
kind: Service
metadata:
  name:  sanjo-rtp-service
  namespace: sanjo
spec:
  type: NodePort
  selector:
    app: sanjo-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000